
development:
  database: Chatter_dev
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: localhost
  socket: /var/run/mysqld/mysqld.sock
